<a href="https://colab.research.google.com/github/kingbingodbin/NLP_models/blob/main/XLnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils
import pandas as pd
import os

In [ ]:
import torchtext
import io

In [ ]:
torchtext.datasets.language_modeling.WikiText2

torchtext.datasets.language_modeling.WikiText2

In [ ]:
WikiText2()

TypeError: ignored

In [ ]:
#keeping clicking

function KeepClicking(){
console.log("Clicking");
document.querySelector("colab-connect-button").click()
}
var jbRandom = Math.random();
setInterval(KeepClicking,Math.floor( jbRandom * 40000 + 40000 ))

In [ ]:
import tensorflow_datasets as tfds

In [ ]:
ds = tfds.load('glue', split='train', as_supervised=False, shuffle_files=False)

In [ ]:
for i in ds:
  print(i)

{'idx': <tf.Tensor: shape=(), dtype=int32, numpy=1680>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sentence': <tf.Tensor: shape=(), dtype=string, numpy=b'It is this hat that it is certain that he was wearing.'>}
{'idx': <tf.Tensor: shape=(), dtype=int32, numpy=1456>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sentence': <tf.Tensor: shape=(), dtype=string, numpy=b'Her efficient looking up of the answer pleased the boss.'>}
{'idx': <tf.Tensor: shape=(), dtype=int32, numpy=4223>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sentence': <tf.Tensor: shape=(), dtype=string, numpy=b'Both the workers will wear carnations.'>}
{'idx': <tf.Tensor: shape=(), dtype=int32, numpy=4093>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sentence': <tf.Tensor: shape=(), dtype=string, numpy=b'John enjoyed drawing trees for his syntax homework.'>}
{'idx': <tf.Tensor: shape=(), dtype=int32, numpy=7111>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sentence':

KeyboardInterrupt: ignored

In [ ]:
aa.load()

AttributeError: ignored

In [ ]:
np.array([1,2,3]).shape()

TypeError: ignored

In [ ]:
ddd = aa(a = np.array([1,2,4,5]),b=np.array([1,2,4,5]))

In [ ]:
exec('b=ddd.a.sum()')

In [ ]:
len(np.array([1,2,3]))

3

In [ ]:
sample_dict.get('aa')

12

In [ ]:
sample_dict = {'aa': 12, 'bb':13}

In [ ]:
'list is list'.split(' ')

['list', 'is', 'list']

In [ ]:
dtype = torch.float
device = torch.device("cpu")

In [ ]:
#활용된 잡지식

#자동으로 추가해야할 내용들
#To avoid clutter, we omit the implementation details including multi-head attention, residual connection, layer normalization and position-wise feed-forward as used in Transformer(-XL). The details are included in Appendix A.2 for reference

#데이터 로딩
#data loading
# https://tutorials.pytorch.kr/beginner/data_loading_tutorial.html

#함수 오버라이딩 방법
#super(MyModel, self).__init__()

#einstein summation
#https://rockt.github.io/2018/04/30/einsum

#defining method with string
#https://stackoverflow.com/questions/11553721/using-a-string-variable-as-a-variable-name

#kwargs,args
#https://brunch.co.kr/@princox/180

In [ ]:
# Two-stream attention cell
#input : q_size, k_size, v_size, segment_index, attention_size, heads =8, **kwargs = {init_Qstream_q_LT_weight, init_Qstream_q_K_weight,init_Qstream_q_R_weight, init_Qstream_k_E_LT_weight, init_Qstream_k_R_LT_weight, init_Qstream_v_LT_weight,
#                                                                            init_Qstream_segment_same_weight, init_Qstream_segment_notsame_weight, init_Qstream_segment_bias, init_Qstream_output_weight,
#                                                                            init_Cstream_q_LT_weight, init_Cstream_q_K_weight,init_Cstream_q_R_weight, init_Cstream_k_E_LT_weight, init_Cstream_k_R_LT_weight, init_Cstream_v_LT_weight,
#                                                                            init_Cstream_segment_same_weight, init_Cstream_segment_notsame_weight, init_Cstream_segment_bias, init_Cstream_output_weight}
#

#operation : q_LT, k_LT, v_LT, segmentation, permutation(optional), masking, relative_position_encoding, segment_encoding, cal_content_attention, cal_query_attention, memorise

#properties : Qstream_q_LT_weight, Qstream_q_K_weight,Qstream_q_R_weight, Qstream_k_E_LT_weight, Qstream_k_R_LT_weight, Qstream_v_LT_weight,
#             Qstream_segment_same_weight, Qstream_segment_notsame_weight, Qstream_segment_bias, Qstream_output_weight,
#             Cstream_q_LT_weight, Cstream_q_K_weight,Cstream_q_R_weight, Cstream_k_E_LT_weight, Cstream_k_R_LT_weight, Cstream_v_LT_weight,
#             Cstream_segment_same_weight, Cstream_segment_notsame_weight, Cstream_segment_bias, Cstream_output_weight content_attention, query_attention, content_memory, query_memory

#output : Dq vector(s)



In [ ]:
class create_PLM_input(data_utils.Dataset):
  def __init__(self, data, target_csv, word_dict = False, sep_by_lines = False, segment_len = False, do_shuffle=True):
    super(create_PLM_input, self).__init__()
    
    self.target_csv = pd.read_csv(traget_csv)
    self.dat_shape = data.shape
    self.root_dir = root_dir
    self.segment_len = segment_len
    self.word_dict = False
    self.data = data

    if do_shuffle:
      shuffle()
    
    segmentation()

  def segmentation(self):
    self.segments = 

  def __getitem__(self, idx):
    if torch.is_tensor(idx):
      idx = idx.tolist()

    doc_paths = os.path.join(self.root_dir, self.target_csv.iloc[idx, 0])
    for doc_path in doc_paths
    doc_file = open(doc_path, 'r')

    lines = doc_file.readlines()

    if word_dict:
      for line in lines:
        for 

    


    doc_file.close()


    f = open("C:/doit/새파일.txt", 'r')


      landmarks = self.landmarks_frame.iloc[idx, 1:]
      landmarks = np.array([landmarks])
      landmarks = landmarks.astype('float').reshape(-1, 2)
      sample = {'image': image, 'landmarks': landmarks}

    return sample

  def __len__(self):
    return len(self.data)

In [ ]:
class create_PLM_input_inmemory(data_utils.Dataset):


In [ ]:
# https://tutorials.pytorch.kr/beginner/data_loading_tutorial.html

perred


In [ ]:
a= torch.nn

In [ ]:
def shuffle()

def permutate()

def rel_position_encoding():

def masking():

In [ ]:
if not a:
  print(1)

In [ ]:
class Two_stream_attention(nn):
  def __init__(self, q_size, k_size, v_size, attention_size = False, heads =8, **kwargs):
    super(Two_stream_attention, self).__init__() 
      

    self.segment_index = segment_index

    #initialize params
    self.initialize_params(self, q_size, k_size, v_size, attention_size, heads)

  def initialize_params(self, q_size, k_size, v_size, attention_size, heads):
    self.Qstream_q_LT_weight = nn.Linear()
    self.Qstream_q_K_weight = 
    self.Qstream_q_R_weight = 
    
    self.Qstream_k_E_LT_weight = 
    self.Qstream_k_R_LT_weight = 
    self.Qstream_v_LT_weight = 
    
    self.Qstream_segment_same_weight = 
    self.Qstream_segment_notsame_weight = 
    self.Qstream_segment_bias = 
    
    self.Qstream_output_weight = 

    self.Cstream_q_LT_weight = 
    self.Cstream_q_K_weight = 
    self.Cstream_q_R_weight = 
    
    self.Cstream_k_E_LT_weight = 
    self.Cstream_k_R_LT_weight = 
    self.Cstream_v_LT_weight = 

    self.Cstream_segment_same_weight = 
    self.Cstream_segment_notsame_weight = 
    self.Cstream_segment_bias = 
    
    self.Cstream_output_weight =

  def set_params(self,**kwargs):
    for i,j in kwargs.items():
      setattr(self, i, j)
      explicitly_defined_vars.append(i)

  def forward(self, input, do_parm = False, rel_position = False):
    
    #record position
    if not rel_position:
      self.rel_position = rel_position_encoding(input)
    else:
      self.rel_position = rel_position

    #permutation
    if do_parm:
      self.permutate()

    #get position encoding

    #cal
  def backward(self,??): #클레스 정의하는 법 참조


SyntaxError: ignored

In [ ]:
_#http://nlp.seas.harvard.edu/2018/04/03/attention.html

In [ ]:
##Copyright 2013, Youngbin Jang, All rights reserved.