<a href="https://colab.research.google.com/github/kingbingodbin/NLP_models/blob/main/XLnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils
from torchtext.data.utils import get_tokenizer
from torchtext.data import Field
import pandas as pd
import os

In [2]:
import torchtext
import io

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [113]:
import os
os.listdir('drive/My Drive/datasets/wikitext-2')

['wiki.valid.tokens', 'wiki.test.tokens', 'wiki.train.tokens']

In [116]:
#install package for subword tokenizer
!pip install revtok

In [121]:
get_tokenizer("revtok")

<function revtok.tokenizer.tokenize>

In [122]:
dataset_base_path = 'drive/My Drive/datasets/'
path = dataset_base_path + 'wikitext-2/'
TEXT = torchtext.data.Field(tokenize=get_tokenizer("revtok"),
                            init_token='<sos>',
                            eos_token='<eos>',
                            lower=True)

In [123]:
dtype = torch.float
device = torch.device("cpu")

In [124]:
tr_dat,val_dat,test_dat = torchtext.datasets.language_modeling.WikiText2.splits(TEXT)

In [128]:
TEXT.build_vocab(tr_dat)

In [129]:
def batchify(data, bsz):
    data = TEXT.numericalize([data.examples[0].text])
    # Divide the dataset into bsz parts.
    nbatch = data.size(0) // bsz
    # Trim off any extra elements that wouldn't cleanly fit (remainders).
    data = data.narrow(0, 0, nbatch * bsz)
    # Evenly divide the data across the bsz batches.
    data = data.view(bsz, -1).t().contiguous()
    return data.to(device)

batch_size = 20
eval_batch_size = 10
train_data = batchify(tr_dat, batch_size)
val_data = batchify(val_dat, eval_batch_size)
test_data = batchify(test_dat, eval_batch_size)

In [177]:
[tr_dat.examples[0].text][0][4000:4800]

[' along ',
 ' the ',
 ' same ',
 ' timeline ',
 ' as ',
 ' the ',
 ' original ',
 ' game ',
 ' and ',
 ' its ',
 ' television ',
 ' anime ',
 ' adaptation ',
 ' , ',
 ' the ',
 ' cast ',
 ' of ',
 ' valkyria ',
 ' chronicles ',
 ' could ',
 ' make ',
 ' appearances ',
 ' , ',
 ' which ',
 ' pleased ',
 ' the ',
 ' team ',
 ' . ',
 ' the ',
 ' opening ',
 ' theme ',
 ' , ',
 ' " ',
 ' <',
 ' unk ',
 '> ',
 ' ( ',
 ' light ',
 ' ) ',
 ' <',
 ' unk ',
 '> ',
 ' " ',
 ' ( ',
 ' <',
 ' unk ',
 '> ',
 ' @ ',
 '- ',
 '@ ',
 ' <',
 ' unk ',
 '> ',
 ' ) ',
 ' , ',
 ' was ',
 ' sung ',
 ' by ',
 ' japanese ',
 ' singer ',
 ' <',
 ' unk ',
 '> ',
 ' . ',
 ' the ',
 ' ending ',
 ' theme ',
 ' , ',
 ' " ',
 ' <',
 ' unk ',
 '> ',
 ' the ',
 ' flowers ',
 ' of ',
 ' light ',
 ' will ',
 ' bloom ',
 ' " ',
 ' ( ',
 ' <',
 ' unk ',
 '> ',
 ' , ',
 ' <',
 ' unk ',
 '> ',
 ' <',
 ' unk ',
 '> ',
 ' <',
 ' unk ',
 '> ',
 ' no ',
 ' <',
 ' unk ',
 '> ',
 ' ) ',
 ' , ',
 ' was ',
 ' sung ',
 ' by ',
 ' <'

In [149]:
train_data[0]

tensor([    7,    29,  4031,  2997,   447,  3285,     4,   133,   444,    36,
         3745,     3,   838,     6, 24073,  1484,     4,    25, 13603,    71])

In [150]:
train_data[1]

tensor([    7,  1781,    20,   179, 15130,   765,   632,    59,   490,  6997,
           27,     7,     6,     4,   480,  5051,    60,    15,     8,     9])

In [148]:
TEXT.

SyntaxError: ignored

In [64]:
en_textfield.build_vocab(tr_dat, min_freq = 2)

In [67]:
BATCH_SIZE = 128

train_iterator, valid_iterator, test_iterator = BucketIterator.splits(
    (tr_dat, val_dat, test_dat),
    batch_size = BATCH_SIZE,
    device = device)

In [83]:
for i,batch in train_iterator:
  aa = batch
  bb = i

In [91]:
bb

(tensor([[   9,   11, 3875,  ...,    4,    9,    9]]), tensor([2088628]))

In [ ]:
import tensorflow_datasets as tfds

In [ ]:
ds = tfds.load('glue', split='train', as_supervised=False, shuffle_files=False)

In [ ]:
for i in ds:
  print(i)

NameError: ignored

In [ ]:
aa.load()

AttributeError: ignored

In [ ]:
np.array([1,2,3]).shape()

TypeError: ignored

In [ ]:
ddd = aa(a = np.array([1,2,4,5]),b=np.array([1,2,4,5]))

In [ ]:
exec('b=ddd.a.sum()')

In [ ]:
len(np.array([1,2,3]))

3

In [ ]:
sample_dict.get('aa')

12

In [ ]:
sample_dict = {'aa': 12, 'bb':13}

In [ ]:
'list is list'.split(' ')

['list', 'is', 'list']

In [16]:
dtype = torch.float
device = torch.device("cpu")

In [ ]:
#활용된 잡지식

#pytorch dataset 불러오기 
#https://pytorch.org/text/datasets.html

#자동으로 추가해야할 내용들
#To avoid clutter, we omit the implementation details including multi-head attention, residual connection, layer normalization and position-wise feed-forward as used in Transformer(-XL). The details are included in Appendix A.2 for reference

#데이터 로딩
#data loading
# https://tutorials.pytorch.kr/beginner/data_loading_tutorial.html

#함수 오버라이딩 방법
#super(MyModel, self).__init__()

#einstein summation
#https://rockt.github.io/2018/04/30/einsum

#defining method with string
#https://stackoverflow.com/questions/11553721/using-a-string-variable-as-a-variable-name

#kwargs,args
#https://brunch.co.kr/@princox/180

In [ ]:
# Two-stream attention cell
#input : q_size, k_size, v_size, segment_index, attention_size, heads =8, **kwargs = {init_Qstream_q_LT_weight, init_Qstream_q_K_weight,init_Qstream_q_R_weight, init_Qstream_k_E_LT_weight, init_Qstream_k_R_LT_weight, init_Qstream_v_LT_weight,
#                                                                            init_Qstream_segment_same_weight, init_Qstream_segment_notsame_weight, init_Qstream_segment_bias, init_Qstream_output_weight,
#                                                                            init_Cstream_q_LT_weight, init_Cstream_q_K_weight,init_Cstream_q_R_weight, init_Cstream_k_E_LT_weight, init_Cstream_k_R_LT_weight, init_Cstream_v_LT_weight,
#                                                                            init_Cstream_segment_same_weight, init_Cstream_segment_notsame_weight, init_Cstream_segment_bias, init_Cstream_output_weight}
#

#operation : q_LT, k_LT, v_LT, segmentation, permutation(optional), masking, relative_position_encoding, segment_encoding, cal_content_attention, cal_query_attention, memorise

#properties : Qstream_q_LT_weight, Qstream_q_K_weight,Qstream_q_R_weight, Qstream_k_E_LT_weight, Qstream_k_R_LT_weight, Qstream_v_LT_weight,
#             Qstream_segment_same_weight, Qstream_segment_notsame_weight, Qstream_segment_bias, Qstream_output_weight,
#             Cstream_q_LT_weight, Cstream_q_K_weight,Cstream_q_R_weight, Cstream_k_E_LT_weight, Cstream_k_R_LT_weight, Cstream_v_LT_weight,
#             Cstream_segment_same_weight, Cstream_segment_notsame_weight, Cstream_segment_bias, Cstream_output_weight content_attention, query_attention, content_memory, query_memory

#output : Dq vector(s)



In [ ]:
class create_PLM_input(data_utils.Dataset):
  def __init__(self, data, target_csv, word_dict = False, sep_by_lines = False, segment_len = False, do_shuffle=True):
    super(create_PLM_input, self).__init__()
    
    self.target_csv = pd.read_csv(traget_csv)
    self.dat_shape = data.shape
    self.root_dir = root_dir
    self.segment_len = segment_len
    self.word_dict = False
    self.data = data

    if do_shuffle:
      shuffle()
    
    segmentation()

  def segmentation(self):
    self.segments = 

  def __getitem__(self, idx):
    if torch.is_tensor(idx):
      idx = idx.tolist()

    doc_paths = os.path.join(self.root_dir, self.target_csv.iloc[idx, 0])
    for doc_path in doc_paths
    doc_file = open(doc_path, 'r')

    lines = doc_file.readlines()

    if word_dict:
      for line in lines:
        for 

    


    doc_file.close()


    f = open("C:/doit/새파일.txt", 'r')


      landmarks = self.landmarks_frame.iloc[idx, 1:]
      landmarks = np.array([landmarks])
      landmarks = landmarks.astype('float').reshape(-1, 2)
      sample = {'image': image, 'landmarks': landmarks}

    return sample

  def __len__(self):
    return len(self.data)

In [ ]:
class create_PLM_input_inmemory(data_utils.Dataset):


In [ ]:
# https://tutorials.pytorch.kr/beginner/data_loading_tutorial.html

perred


In [ ]:
a= torch.nn

In [ ]:
def shuffle()

def permutate()

def rel_position_encoding():

def masking():

In [ ]:
if not a:
  print(1)

In [ ]:
class Two_stream_attention(nn):
  def __init__(self, q_size, k_size, v_size, attention_size = False, heads =8, **kwargs):
    super(Two_stream_attention, self).__init__() 
      

    self.segment_index = segment_index

    #initialize params
    self.initialize_params(self, q_size, k_size, v_size, attention_size, heads)

  def initialize_params(self, q_size, k_size, v_size, attention_size, heads):
    self.Qstream_q_LT_weight = nn.Linear()
    self.Qstream_q_K_weight = 
    self.Qstream_q_R_weight = 
    
    self.Qstream_k_E_LT_weight = 
    self.Qstream_k_R_LT_weight = 
    self.Qstream_v_LT_weight = 
    
    self.Qstream_segment_same_weight = 
    self.Qstream_segment_notsame_weight = 
    self.Qstream_segment_bias = 
    
    self.Qstream_output_weight = 

    self.Cstream_q_LT_weight = 
    self.Cstream_q_K_weight = 
    self.Cstream_q_R_weight = 
    
    self.Cstream_k_E_LT_weight = 
    self.Cstream_k_R_LT_weight = 
    self.Cstream_v_LT_weight = 

    self.Cstream_segment_same_weight = 
    self.Cstream_segment_notsame_weight = 
    self.Cstream_segment_bias = 
    
    self.Cstream_output_weight =

  def set_params(self,**kwargs):
    for i,j in kwargs.items():
      setattr(self, i, j)
      explicitly_defined_vars.append(i)

  def forward(self, input, do_parm = False, rel_position = False):
    
    #record position
    if not rel_position:
      self.rel_position = rel_position_encoding(input)
    else:
      self.rel_position = rel_position

    #permutation
    if do_parm:
      self.permutate()

    #get position encoding

    #cal
  def backward(self,??): #클레스 정의하는 법 참조


SyntaxError: ignored

In [ ]:
_#http://nlp.seas.harvard.edu/2018/04/03/attention.html

In [ ]:
##Copyright 2013, Youngbin Jang, All rights reserved.